"""Add notes field to Meal model

Revision ID: a8ecb76b6e54
Revises: e9d5c7cfc4fe
Create Date: 2025-04-09 23:01:24.105446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ecb76b6e54'
down_revision = 'e9d5c7cfc4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
