"""Update recipe model fields

Revision ID: e9d5c7cfc4fe
Revises: d64a1239dadc
Create Date: 2025-04-09 22:35:16.390388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d5c7cfc4fe'
down_revision = 'd64a1239dadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.alter_column('ingredients',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('ingredients',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('instructions')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
