"""Add plan_id foreign key to Meal

Revision ID: f97bc1006eca
Revises: a8ecb76b6e54
Create Date: 2025-04-12 13:11:48.293439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97bc1006eca'
down_revision = 'a8ecb76b6e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_meal_plan_id', 'meal_plan', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meal_plan_id', type_='foreignkey')
        batch_op.drop_column('plan_id')
        batch_op.drop_column('day_of_week')

    op.drop_table('meal_plan')
    # ### end Alembic commands ###
